### ISSUE TITLE
Some tutorial?

### ISSUE THREAD

**Issue by Pioruniasty** [fandogh/hapi-nuxt#2]
Can u write some tutorial how to connect Hapi with Nuxt using this?

**Comment by pi0** [comment]
@Pioruniasty Sure! I will create a starter template soon. BTW before that, all thing to do is just simply register this plugin & passing nuxt config object (you may require it from nuxt.config.js` as plugin options. Plugin automatically registers `*` to be served with nuxt.

**Comment by Pioruniasty** [comment]
Ok, ok, thanks for quick response 👍 . I'll try then :).

**Comment by Pioruniasty** [comment]
Well .. what I am doing wrong?

Here's my code:

```
const Hapi = require('hapi');
const HapiNuxt = require('hapi-nuxt');

const server = new Hapi.Server();

server.connection({port: 4321});

server.register({
    register: HapiNuxt,
    options: {
        dev: (process.env.NODE_ENV !== 'production')
    }
}, () => {
    server.start();
});
```

and I get error "Cannot read property 'dev' of undefined" at 
```
if (nuxt.options.dev) {
```

**Comment by pi0** [comment]
Opps seems migration typo. I'll fix it ASAP.

**Comment by pi0** [comment]
Docs updated. Please open a new issue if any problem exists with it.
